version: '3.8'

services:
  splitpenny:
    build: .
    ports:
      - 5000:5000
    environment:
      - FASTAPI_CONFIG=development
    volumes:
      - ./splitpenny:/src/splitpenny
    #depends_on:
    #  - db
    #  - adminer
#      - influxdb